# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foodlist',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
